// Copyright 2017 The Go Authors. All rights reserved.
// Copyright 2026 MedDeck LTDA. All Rights Reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in LICENSES/BSD-3-Clause-Go.txt.
//
// Ported from golang.org/x/crypto@v0.46.0/cryptobyte/cryptobyte_test.go
//
// The ASN.1 tests (TestASN1Int64, TestASN1Uint64) and the fixed-size Builder tests
// (TestFixedBuilderLengthPrefixed, TestFixedBuilderPanicReallocate) are absent because
// the corresponding functionality is not ported. See
// docs/decisions/0040-cryptobyte-port-scope.md. TestPreallocatedBuffer is ported with
// the one change described on it.
//
// The Examples of example_test.go are in cryptobyte_example_test.ts.

import { describe, expect, it } from "vitest";
import * as cryptobyte from "./cryptobyte.ts";

// builderBytesEq asserts that the builder's output is exactly want.
function builderBytesEq(b: cryptobyte.Builder, ...want: number[]): void {
	expect(Array.from(b.bytesOrPanic())).toEqual(want);
}

describe("TestContinuationError", () => {
	it("surfaces a BuildError thrown by a continuation from bytes()", () => {
		const errorStr = "TestContinuationError";
		const b = new cryptobyte.Builder();
		b.addUint8LengthPrefixed((b) => {
			b.addUint8(1);
			throw new cryptobyte.BuildError(new Error(errorStr));
		});

		expect(() => b.bytes()).toThrowError(errorStr);
	});
});

describe("TestContinuationNonError", () => {
	it("rethrows anything that is not a BuildError", () => {
		const b = new cryptobyte.Builder();
		expect(() => {
			b.addUint8LengthPrefixed((b) => {
				b.addUint8(1);
				throw new Error("not a BuildError");
			});
		}).toThrowError("not a BuildError");
	});
});

describe("TestGeneratedPanic", () => {
	it("rethrows a fault raised by the runtime inside a continuation", () => {
		const b = new cryptobyte.Builder();
		expect(() => {
			b.addUint8LengthPrefixed(() => {
				// The equivalent of Go's nil-pointer dereference: a fault generated by the
				// runtime rather than by the builder, which must not be swallowed.
				new Uint8Array(-1);
			});
		}).toThrow(RangeError);
	});
});

describe("TestBytes", () => {
	it("round-trips through AddBytes and ReadBytes", () => {
		const b = new cryptobyte.Builder();
		const v = new TextEncoder().encode("foobarbaz");
		b.addBytes(v.subarray(0, 3));
		b.addBytes(v.subarray(3, 4));
		b.addBytes(v.subarray(4, 9));
		builderBytesEq(b, ...Array.from(v));

		const s = new cryptobyte.String(b.bytesOrPanic());
		for (const w of ["foo", "bar", "baz"]) {
			const got = s.readBytes(3);
			if (got === undefined) {
				throw new Error(`ReadBytes() = false, want true (w = ${w})`);
			}
			expect(Array.from(got)).toEqual(Array.from(new TextEncoder().encode(w)));
		}
		expect(s.length).toBe(0);
	});
});

describe("TestUint8", () => {
	it("round-trips", () => {
		const b = new cryptobyte.Builder();
		b.addUint8(42);
		builderBytesEq(b, 42);

		const s = new cryptobyte.String(b.bytesOrPanic());
		expect(s.readUint8()).toBe(42);
		expect(s.length).toBe(0);
	});
});

describe("TestUint16", () => {
	it("round-trips", () => {
		const b = new cryptobyte.Builder();
		b.addUint16(65534);
		builderBytesEq(b, 255, 254);

		const s = new cryptobyte.String(b.bytesOrPanic());
		expect(s.readUint16()).toBe(65534);
		expect(s.length).toBe(0);
	});
});

describe("TestUint24", () => {
	it("round-trips", () => {
		const b = new cryptobyte.Builder();
		b.addUint24(0xfffefd);
		builderBytesEq(b, 255, 254, 253);

		const s = new cryptobyte.String(b.bytesOrPanic());
		expect(s.readUint24()).toBe(0xfffefd);
		expect(s.length).toBe(0);
	});
});

describe("TestUint24Truncation", () => {
	it("silently truncates the highest byte of the 32-bit input", () => {
		const b = new cryptobyte.Builder();
		b.addUint24(0x10111213);
		builderBytesEq(b, 0x11, 0x12, 0x13);
	});
});

describe("TestUint32", () => {
	it("round-trips", () => {
		const b = new cryptobyte.Builder();
		b.addUint32(0xfffefdfc);
		builderBytesEq(b, 255, 254, 253, 252);

		const s = new cryptobyte.String(b.bytesOrPanic());
		expect(s.readUint32()).toBe(0xfffefdfc);
		expect(s.length).toBe(0);
	});
});

describe("TestUint48", () => {
	it("round-trips", () => {
		const b = new cryptobyte.Builder();
		const u = 0xfefcff3cfdfcn;
		b.addUint48(u);
		builderBytesEq(b, 254, 252, 255, 60, 253, 252);

		const s = new cryptobyte.String(b.bytesOrPanic());
		expect(s.readUint48()).toBe(u);
		expect(s.length).toBe(0);
	});
});

describe("TestUint64", () => {
	it("round-trips", () => {
		const b = new cryptobyte.Builder();
		b.addUint64(0xf2fefefcff3cfdfcn);
		builderBytesEq(b, 242, 254, 254, 252, 255, 60, 253, 252);

		const s = new cryptobyte.String(b.bytesOrPanic());
		expect(s.readUint64()).toBe(0xf2fefefcff3cfdfcn);
		expect(s.length).toBe(0);
	});
});

describe("TestUMultiple", () => {
	it("round-trips a mixture of widths", () => {
		const b = new cryptobyte.Builder();
		b.addUint8(23);
		b.addUint32(0xfffefdfc);
		b.addUint16(42);
		builderBytesEq(b, 23, 255, 254, 253, 252, 0, 42);

		const s = new cryptobyte.String(b.bytesOrPanic());
		const x = s.readUint8();
		const y = s.readUint32();
		const z = s.readUint16();
		expect(x).toBe(23);
		expect(y).toBe(0xfffefdfc);
		expect(z).toBe(42);
		expect(s.length).toBe(0);
	});
});

describe("TestUint8LengthPrefixedSimple", () => {
	it("backfills the length of a single child", () => {
		const b = new cryptobyte.Builder();
		b.addUint8LengthPrefixed((c) => {
			c.addUint8(23);
			c.addUint8(42);
		});
		builderBytesEq(b, 2, 23, 42);

		const base = new cryptobyte.String(b.bytesOrPanic());
		const child = base.readUint8LengthPrefixed();
		if (child === undefined) {
			throw new Error("parsing failed");
		}
		const x = child.readUint8();
		const y = child.readUint8();
		expect(x).toBe(23);
		expect(y).toBe(42);
		expect(base.length).toBe(0);
		expect(child.length).toBe(0);
	});
});

describe("TestUint8LengthPrefixedMulti", () => {
	it("backfills the length of several sibling children", () => {
		const b = new cryptobyte.Builder();
		b.addUint8LengthPrefixed((c) => {
			c.addUint8(23);
			c.addUint8(42);
		});
		b.addUint8(5);
		b.addUint8LengthPrefixed((c) => {
			c.addUint8(123);
			c.addUint8(234);
		});
		builderBytesEq(b, 2, 23, 42, 5, 2, 123, 234);

		const s = new cryptobyte.String(b.bytesOrPanic());
		const first = s.readUint8LengthPrefixed();
		if (first === undefined) {
			throw new Error("parsing failed");
		}
		const u = first.readUint8();
		const v = first.readUint8();
		const w = s.readUint8();
		const second = s.readUint8LengthPrefixed();
		if (second === undefined) {
			throw new Error("parsing failed");
		}
		const x = second.readUint8();
		const y = second.readUint8();
		expect([u, v, w, x, y]).toEqual([23, 42, 5, 123, 234]);
		expect(s.length).toBe(0);
		expect(second.length).toBe(0);
	});
});

describe("TestUint8LengthPrefixedNested", () => {
	it("backfills the lengths of nested children", () => {
		const b = new cryptobyte.Builder();
		b.addUint8LengthPrefixed((c) => {
			c.addUint8(5);
			c.addUint8LengthPrefixed((d) => {
				d.addUint8(23);
				d.addUint8(42);
			});
			c.addUint8(123);
		});
		builderBytesEq(b, 5, 5, 2, 23, 42, 123);

		const base = new cryptobyte.String(b.bytesOrPanic());
		const child1 = base.readUint8LengthPrefixed();
		if (child1 === undefined) {
			throw new Error("parsing base failed");
		}
		const u = child1.readUint8();
		const child2 = child1.readUint8LengthPrefixed();
		if (child2 === undefined) {
			throw new Error("parsing child1 failed");
		}
		const x = child1.readUint8();
		const v = child2.readUint8();
		const w = child2.readUint8();
		expect([u, v, w, x]).toEqual([5, 23, 42, 123]);
		expect(base.length).toBe(0);
		expect(child1.length).toBe(0);
		expect(child2.length).toBe(0);
	});
});

describe("TestPreallocatedBuffer", () => {
	it("appends into the caller's buffer until it is outgrown", () => {
		// Port note: Go builds on `buf[0:0]`, a zero-length slice with room behind it. A
		// Uint8Array has no such thing, so the same state is reached by handing over the
		// array and rolling its length back to zero with unwrite(), as newBuilder's comment
		// describes.
		const buf = new Uint8Array(5);
		const b = cryptobyte.newBuilder(buf);
		b.unwrite(buf.length);
		b.addUint8(1);
		b.addUint8LengthPrefixed((c) => {
			c.addUint8(3);
			c.addUint8(4);
		});
		b.addUint16(1286); // Outgrow buf by one byte.
		expect(Array.from(buf)).toEqual([1, 2, 3, 4, 0]);
		builderBytesEq(b, 1, 2, 3, 4, 5, 6);
	});
});

describe("TestWriteWithPendingChild", () => {
	it("throws when an ancestor is written to while a child is pending", () => {
		const b = new cryptobyte.Builder();
		b.addUint8LengthPrefixed((c) => {
			c.addUint8LengthPrefixed(() => {
				expect(() => c.addUint8(2)).toThrowError("cryptobyte: attempted write while child is pending");
				expect(() => b.addUint8(2)).toThrowError("cryptobyte: attempted write while child is pending");
			});

			expect(() => b.addUint8(2)).toThrowError("cryptobyte: attempted write while child is pending");
		});
	});
});

describe("TestSetError", () => {
	it("makes bytes() report the error that was set", () => {
		const errorStr = "TestSetError";
		const b = new cryptobyte.Builder();
		b.setError(new Error(errorStr));

		expect(() => b.bytes()).toThrowError(errorStr);
	});
});

describe("TestUnwrite", () => {
	it("rolls back bytes written directly to the builder", () => {
		const b = new cryptobyte.Builder();
		b.addBytes(Uint8Array.of(1, 2, 3, 4, 5));
		b.unwrite(2);
		builderBytesEq(b, 1, 2, 3);

		expect(() => b.unwrite(4)).toThrowError("cryptobyte: attempted to unwrite more than was written");
	});

	it("throws when a child unwrites more than it wrote", () => {
		const b = new cryptobyte.Builder();
		b.addBytes(Uint8Array.of(1, 2, 3, 4, 5));
		b.addUint8LengthPrefixed((c) => {
			c.addBytes(Uint8Array.of(1, 2, 3, 4, 5));
			expect(() => c.unwrite(6)).toThrowError("cryptobyte: attempted to unwrite more than was written");
		});
	});

	it("throws when a parent unwrites while a child is pending", () => {
		const b = new cryptobyte.Builder();
		b.addBytes(Uint8Array.of(1, 2, 3, 4, 5));
		b.addUint8LengthPrefixed(() => {
			expect(() => b.unwrite(2)).toThrowError("cryptobyte: attempted unwrite while child is pending");
		});
	});

	it("throws on a negative count", () => {
		const b = new cryptobyte.Builder();
		b.addBytes(Uint8Array.of(1, 2, 3));
		expect(() => b.unwrite(-1)).toThrowError("cryptobyte: attempted to unwrite negative number of bytes");
	});
});

// The tests below have no upstream counterpart. They pin the deferred-length-prefix
// behaviour that ctonly/ct.ts and ct_only.ts depend on: prefix widths, nesting,
// empty children and the overflow error.

describe("length prefixes", () => {
	it("writes a big-endian length for each prefix width", () => {
		const cases: {
			name: string;
			add: (b: cryptobyte.Builder, f: cryptobyte.BuilderContinuation) => void;
			n: number;
			wantPrefix: number[];
		}[] = [
			{
				name: "uint8",
				add: (b, f) => b.addUint8LengthPrefixed(f),
				n: 3,
				wantPrefix: [0x03],
			},
			{
				name: "uint16",
				add: (b, f) => b.addUint16LengthPrefixed(f),
				n: 300,
				wantPrefix: [0x01, 0x2c],
			},
			{
				name: "uint24",
				add: (b, f) => b.addUint24LengthPrefixed(f),
				n: 70000,
				wantPrefix: [0x01, 0x11, 0x70],
			},
			{
				name: "uint32",
				add: (b, f) => b.addUint32LengthPrefixed(f),
				n: 70000,
				wantPrefix: [0x00, 0x01, 0x11, 0x70],
			},
		];
		for (const c of cases) {
			const b = new cryptobyte.Builder();
			c.add(b, (child) => {
				child.addBytes(new Uint8Array(c.n).fill(0xaa));
			});
			const got = b.bytesOrPanic();
			expect(Array.from(got.subarray(0, c.wantPrefix.length)), c.name).toEqual(c.wantPrefix);
			expect(got.length, c.name).toBe(c.wantPrefix.length + c.n);
		}
	});

	it("writes a zero length for an empty child", () => {
		const b = new cryptobyte.Builder();
		b.addUint8LengthPrefixed(() => {});
		b.addUint16LengthPrefixed(() => {});
		b.addUint24LengthPrefixed(() => {});
		builderBytesEq(b, 0, 0, 0, 0, 0, 0);
	});

	it("writes a zero length for an empty child nested inside another child", () => {
		const b = new cryptobyte.Builder();
		b.addUint16LengthPrefixed((c) => {
			c.addUint8LengthPrefixed(() => {});
		});
		builderBytesEq(b, 0, 1, 0);
	});

	it("nests prefixes of differing widths", () => {
		const b = new cryptobyte.Builder();
		b.addUint24LengthPrefixed((c) => {
			c.addUint8(0xff);
			c.addUint16LengthPrefixed((d) => {
				d.addUint8LengthPrefixed((e) => {
					e.addBytes(Uint8Array.of(1, 2, 3));
				});
			});
		});
		// 24-bit prefix over: ff, then a 16-bit prefix over (an 8-bit prefix over 3 bytes).
		builderBytesEq(b, 0x00, 0x00, 0x07, 0xff, 0x00, 0x04, 0x03, 1, 2, 3);
	});

	it("reports a child that overflows an 8-bit prefix", () => {
		const b = new cryptobyte.Builder();
		b.addUint8LengthPrefixed((c) => {
			c.addBytes(new Uint8Array(256));
		});
		expect(() => b.bytes()).toThrowError("cryptobyte: pending child length 256 exceeds 1-byte length prefix");
	});

	it("reports a child that overflows a 16-bit prefix", () => {
		const b = new cryptobyte.Builder();
		b.addUint16LengthPrefixed((c) => {
			c.addBytes(new Uint8Array(1 << 16));
		});
		expect(() => b.bytes()).toThrowError("cryptobyte: pending child length 65536 exceeds 2-byte length prefix");
	});

	it("accepts a child that exactly fills its prefix width", () => {
		const b = new cryptobyte.Builder();
		b.addUint8LengthPrefixed((c) => {
			c.addBytes(new Uint8Array(255));
		});
		const got = b.bytesOrPanic();
		expect(got.length).toBe(256);
		expect(got[0]).toBe(255);
	});

	it("propagates an overflow from an inner child to the outermost builder", () => {
		const b = new cryptobyte.Builder();
		b.addUint16LengthPrefixed((c) => {
			c.addUint8LengthPrefixed((d) => {
				d.addBytes(new Uint8Array(300));
			});
		});
		expect(() => b.bytes()).toThrowError("cryptobyte: pending child length 300 exceeds 1-byte length prefix");
	});

	it("ignores writes made after an error", () => {
		const errorStr = "sticky";
		const b = new cryptobyte.Builder();
		b.addUint8(1);
		b.setError(new Error(errorStr));
		b.addUint8(2);
		b.addUint16LengthPrefixed((c) => {
			c.addUint8(3);
		});
		expect(() => b.bytes()).toThrowError(errorStr);
	});

	it("propagates an error set on a child by setError", () => {
		const errorStr = "child error";
		const b = new cryptobyte.Builder();
		b.addUint16LengthPrefixed((c) => {
			c.setError(new Error(errorStr));
		});
		expect(() => b.bytes()).toThrowError(errorStr);
	});
});

describe("String reads", () => {
	it("reports failure and does not advance on a short read", () => {
		const s = new cryptobyte.String(Uint8Array.of(1, 2, 3));
		expect(s.readUint32()).toBeUndefined();
		expect(s.length).toBe(3);
		expect(s.readBytes(4)).toBeUndefined();
		expect(s.length).toBe(3);
		expect(s.skip(4)).toBe(false);
		expect(s.length).toBe(3);
		expect(s.readUint24()).toBe(0x010203);
		expect(s.empty()).toBe(true);
	});

	it("rejects a negative read", () => {
		const s = new cryptobyte.String(Uint8Array.of(1, 2, 3));
		expect(s.skip(-1)).toBe(false);
		expect(s.readBytes(-1)).toBeUndefined();
		expect(s.length).toBe(3);
	});

	it("reports failure when a length prefix promises more than remains", () => {
		expect(new cryptobyte.String(Uint8Array.of(3, 1, 2)).readUint8LengthPrefixed()).toBeUndefined();
		expect(new cryptobyte.String(Uint8Array.of(0x00, 0x03, 1, 2)).readUint16LengthPrefixed()).toBeUndefined();
		expect(new cryptobyte.String(Uint8Array.of(0x00, 0x00, 0x03, 1, 2)).readUint24LengthPrefixed()).toBeUndefined();
	});

	it("reports failure when the length prefix itself is truncated", () => {
		expect(new cryptobyte.String(new Uint8Array(0)).readUint8LengthPrefixed()).toBeUndefined();
		expect(new cryptobyte.String(Uint8Array.of(0x00)).readUint16LengthPrefixed()).toBeUndefined();
		expect(new cryptobyte.String(Uint8Array.of(0x00, 0x00)).readUint24LengthPrefixed()).toBeUndefined();
	});

	it("reads an empty length-prefixed value", () => {
		const s = new cryptobyte.String(Uint8Array.of(0, 0, 0, 0, 0, 0));
		const a = s.readUint8LengthPrefixed();
		const c = s.readUint16LengthPrefixed();
		const d = s.readUint24LengthPrefixed();
		expect(a?.empty()).toBe(true);
		expect(c?.empty()).toBe(true);
		expect(d?.empty()).toBe(true);
		expect(s.empty()).toBe(true);
	});

	it("exposes the unread bytes", () => {
		const s = new cryptobyte.String(Uint8Array.of(1, 2, 3, 4));
		expect(s.skip(1)).toBe(true);
		expect(Array.from(s.bytes())).toEqual([2, 3, 4]);
	});

	it("starts empty when constructed with no argument", () => {
		const s = new cryptobyte.String();
		expect(s.empty()).toBe(true);
		expect(s.length).toBe(0);
	});

	it("fails every read on the zero value, a nil String, even of 0 bytes", () => {
		// Go: `var s cryptobyte.String; s.Skip(0)` is false, because read(0) slices nil to nil.
		const s = new cryptobyte.String();
		expect(s.skip(0)).toBe(false);
		expect(s.readBytes(0)).toBeUndefined();
		expect(s.readUint8()).toBeUndefined();
		expect(s.readUint8LengthPrefixed()).toBeUndefined();
		expect(new cryptobyte.String(undefined).skip(0)).toBe(false);
	});

	it("succeeds in reading 0 bytes from an empty String that is not nil", () => {
		const s = new cryptobyte.String(new Uint8Array(0));
		expect(s.skip(0)).toBe(true);
		expect(s.readBytes(0)?.length).toBe(0);
		expect(s.readUint8()).toBeUndefined();
	});

	it("stays non-nil once every byte has been read", () => {
		const s = new cryptobyte.String(Uint8Array.of(1));
		expect(s.skip(1)).toBe(true);
		expect(s.empty()).toBe(true);
		expect(s.skip(0)).toBe(true);
		expect(s.readBytes(0)?.length).toBe(0);
	});

	it("hands out an empty length-prefixed value that is not nil", () => {
		const v = new cryptobyte.String(Uint8Array.of(0, 0)).readUint16LengthPrefixed();
		expect(v?.skip(0)).toBe(true);
	});
});

describe("newBuilder", () => {
	it("appends to the supplied buffer", () => {
		const b = cryptobyte.newBuilder(Uint8Array.of(0xde, 0xad));
		b.addUint8(0xbe);
		b.addUint8(0xef);
		builderBytesEq(b, 0xde, 0xad, 0xbe, 0xef);
	});

	it("reallocates on the first append, leaving a buffer that is full as it was", () => {
		// What Go does for NewBuilder(buf) when len(buf) == cap(buf).
		const buf = Uint8Array.of(1, 2, 3, 4);
		const b = cryptobyte.newBuilder(buf);
		b.addUint8(9);
		expect(Array.from(buf)).toEqual([1, 2, 3, 4]);
		builderBytesEq(b, 1, 2, 3, 4, 9);
	});

	it("writes into the caller's buffer once unwrite has made room, as Go's append does", () => {
		const buf = Uint8Array.of(1, 2, 3, 4);
		const b = cryptobyte.newBuilder(buf);
		b.unwrite(4);
		b.addUint8(9);
		expect(Array.from(buf)).toEqual([9, 2, 3, 4]);
		builderBytesEq(b, 9);
	});

	it("moves to a new array when unwrite has left too little room, leaving the rest of the caller's buffer alone", () => {
		const buf = Uint8Array.of(1, 2, 3, 4);
		const b = cryptobyte.newBuilder(buf);
		b.unwrite(1);
		b.addBytes(Uint8Array.of(7, 8));
		expect(Array.from(buf)).toEqual([1, 2, 3, 4]);
		builderBytesEq(b, 1, 2, 3, 7, 8);
	});
});
