// Copyright 2026 MedDeck LTDA. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Tests for the net/url stand-in. Every expected value is what Go 1.25.5 returned for the
// same input: url.Parse's error, or String(), JoinPath("/add-checkpoint").String(), Host (as
// hex) and Scheme. fixtures/data/differential_gostd.json (section "url") holds 3,000 more,
// generated by the fixture generator; the bracketed hosts here are the ones it cannot hold,
// because Go releases before 1.24.8 and 1.25.2 (CVE-2025-47912) read them differently
// (docs/decisions/0241-witness-policy-urls-parsed-as-go-parses-them.md).

import { describe, expect, it } from "vitest";
import { bytesToHex } from "../../testonly/fixtures.ts";
import { EscapeError, parse, URLError } from "./url.ts";

type Row =
	| readonly [raw: string, err: string]
	| readonly [raw: string, err: "", str: string, joined: string, hostHex: string, scheme: string];

const goResults: readonly Row[] = [
	["https://[1.2.3.4]/", 'parse "https://[1.2.3.4]/": invalid IP-literal'],
	["https://[v1.x]/", 'parse "https://[v1.x]/": invalid host: ParseAddr("v1.x"): unexpected character (at "v1.x")'],
	["https://a[b]/", 'parse "https://a[b]/": invalid host: ParseAddr("b"): unable to parse IP'],
	[
		"https://[fe80::1%25]/x",
		'parse "https://[fe80::1%25]/x": invalid host: ParseAddr("fe80::1%"): zone must be a non-empty string',
	],
	["https://[]/x", 'parse "https://[]/x": invalid host: ParseAddr(""): unable to parse IP'],
	[
		"https://[::1]:8080/x",
		"",
		"https://[::1]:8080/x",
		"https://[::1]:8080/x/add-checkpoint",
		"5b3a3a315d3a38303830",
		"https",
	],
	[
		"https://[fe80::1%25eth0]/x",
		"",
		"https://[fe80::1%25eth0]/x",
		"https://[fe80::1%25eth0]/x/add-checkpoint",
		"5b666538303a3a3125657468305d",
		"https",
	],
	[
		"https://[::ffff:1.2.3.4]/x",
		"",
		"https://[::ffff:1.2.3.4]/x",
		"https://[::ffff:1.2.3.4]/x/add-checkpoint",
		"5b3a3a666666663a312e322e332e345d",
		"https",
	],
	[
		"https://[1::2::3]/",
		'parse "https://[1::2::3]/": invalid host: ParseAddr("1::2::3"): multiple :: in address (at ":3")',
	],
	[
		"https://[12345::]/",
		'parse "https://[12345::]/": invalid host: ParseAddr("12345::"): each group must have 4 or less digits (at "12345::")',
	],
	[
		"https://[::1.2.3.04]/",
		'parse "https://[::1.2.3.04]/": invalid host: ParseAddr("::1.2.3.04"): IPv4 field has octet with leading zero',
	],
	[
		"https://[1:2:3:4:5:6:7:8:9]/",
		'parse "https://[1:2:3:4:5:6:7:8:9]/": invalid host: ParseAddr("1:2:3:4:5:6:7:8:9"): trailing garbage after address (at "9")',
	],
	["https://[%e6]/", 'parse "https://[%e6]/": invalid host: ParseAddr("\\xe6"): unable to parse IP'],
	["*", "", "*", "*/add-checkpoint", "", ""],
	["", "", "", "add-checkpoint", "", ""],
	[
		"https://example.com/a?",
		"",
		"https://example.com/a?",
		"https://example.com/a/add-checkpoint?",
		"6578616d706c652e636f6d",
		"https",
	],
	[
		"https://example.com/a?b?",
		"",
		"https://example.com/a?b?",
		"https://example.com/a/add-checkpoint?b?",
		"6578616d706c652e636f6d",
		"https",
	],
	["https://u%3Ap@h/", "", "https://u%3Ap@h/", "https://u%3Ap@h/add-checkpoint", "68", "https"],
	[
		"https://h/%41%2f?x#a%20b",
		"",
		"https://h/%41%2f?x#a%20b",
		"https://h/%41%2f/add-checkpoint?x#a%20b",
		"68",
		"https",
	],
	["https://h/a#b%zz", 'parse "https://h/a#b%zz": invalid URL escape "%zz"'],
	["http://h/a b", "", "http://h/a%20b", "http://h/a%20b/add-checkpoint", "68", "http"],
	["HTTP://H:/", "", "http://H:/", "http://H:/add-checkpoint", "483a", "http"],
	["https://h:0x1/", 'parse "https://h:0x1/": invalid port ":0x1" after host'],
	["x:/a//b", "", "x:/a//b", "x:/a/b/add-checkpoint", "", "x"],
	["/rel/../x", "", "/rel/../x", "/x/add-checkpoint", "", ""],
	["a/b:c", "", "a/b:c", "a/b:c/add-checkpoint", "", ""],
	["./a:b", "", "./a:b", "./a:b/add-checkpoint", "", ""],
	["//h/p", "", "//h/p", "//h/p/add-checkpoint", "68", ""],
	["///p", "", "///p", "/p/add-checkpoint", "", ""],
	["https://h/../../x/", "", "https://h/../../x/", "https://h/x/add-checkpoint", "68", "https"],
	["https://h/a/./b/../../c/", "", "https://h/a/./b/../../c/", "https://h/c/add-checkpoint", "68", "https"],
	["https://h/x//", "", "https://h/x//", "https://h/x/add-checkpoint", "68", "https"],
	["https://ex%41mple.com/", 'parse "https://ex%41mple.com/": invalid URL escape "%41"'],
	[
		"https://%C3%A4.example/",
		"",
		"https://%C3%A4.example/",
		"https://%C3%A4.example/add-checkpoint",
		"c3a42e6578616d706c65",
		"https",
	],
	["https://example.com/%zé", 'parse "https://example.com/%zé": invalid URL escape "%z\\xc3"'],
	[
		"https://u:p:q@example.com/x",
		"",
		"https://u:p%3Aq@example.com/x",
		"https://u:p%3Aq@example.com/x/add-checkpoint",
		"6578616d706c652e636f6d",
		"https",
	],
	["https://a@b@c/x", "", "https://a%40b@c/x", "https://a%40b@c/x/add-checkpoint", "63", "https"],
	["1a:b/x", 'parse "1a:b/x": first path segment in URL cannot contain colon'],
	["://x", 'parse "://x": missing protocol scheme'],
	["https://ü@example.com/", 'parse "https://ü@example.com/": net/url: invalid userinfo'],
	["https://example.com/\u0001", 'parse "https://example.com/\\x01": net/url: invalid control character in URL'],
	["https://a{b}/", 'parse "https://a{b}/": invalid character "{" in host name'],
];

describe("gostd/url parse, joinPath and string", () => {
	for (const row of goResults) {
		it(`matches Go 1.25.5 on ${JSON.stringify(row[0])}`, () => {
			const [raw, err] = row;
			if (err !== "") {
				expect(() => parse(raw)).toThrow(err);
				return;
			}
			const u = parse(raw);
			const host = bytesToHex(Uint8Array.from(u.host, (c) => c.charCodeAt(0)));
			expect([u.string(), u.joinPath("/add-checkpoint").string(), host, u.scheme]).toEqual(row.slice(2));
		});
	}

	it("throws a URLError that carries Go's Op, URL and Err, with Err as its cause", () => {
		let thrown: unknown;
		try {
			parse("https://example.com/%zz#frag");
		} catch (e) {
			thrown = e;
		}
		expect(thrown).toBeInstanceOf(URLError);
		const e = thrown as URLError;
		expect(e.op).toBe("parse");
		// As Go's Parse, the URL reported for an error before the fragment is the URL without it.
		expect(e.url).toBe("https://example.com/%zz");
		expect(e.err).toBeInstanceOf(EscapeError);
		expect(e.cause).toBe(e.err);
		expect(e.message).toBe('parse "https://example.com/%zz": invalid URL escape "%zz"');
		// An error in the fragment reports the whole URL.
		expect(() => parse("https://example.com/x#%zz")).toThrow(
			'parse "https://example.com/x#%zz": invalid URL escape "%zz"',
		);
	});

	it("leaves the URL it joins onto unchanged", () => {
		const u = parse("https://example.com/a/b/?q");
		const j = u.joinPath("..", "c/");
		expect(u.string()).toBe("https://example.com/a/b/?q");
		expect(j.string()).toBe("https://example.com/a/c/?q");
	});
});
